### ISSUE TITLE
Bug at at group name search (CtGroups.groupNameSearch)

### ISSUE THREAD

**Issue by tnikkine** [Yaron-NI/Kontakt-Public#1]
Hey!

Great helpers, thank you! 

It seems there's typo at line 145 of CtGroups.
`if g.name == g.name then`

Should that actually be 
`if g.name == searchName then`
As is on line 158? 

I'm new to Lua, and was ripping my hair as I couldn't understand why an empty table wasn't empty. It seems due to the above, there's always a "matching" group returned, even if there really is no  name match.

If I'm mistaken here, apologies!

**Comment by faxinadu** [comment]
looks like you are right, if you like please submit a pull request, thanks!

**Comment by tnikkine** [comment]
Oh dear, haven't done that years - don't even have the repo cloned haha. I'll try, let's see if I still remember how..!

**Comment by tnikkine** [comment]
I think I got it done..
