### ISSUE TITLE
Realization in KONTAKT 

### ISSUE THREAD

**Issue by SergeGORA** [Yaron-NI/Kontakt-Public#42]
Hi _

I tested this interesting Script and it works fine on Instrument GUI controls but changes (A, D, S, R for example) are never transmitted inside KONTAKT, for the related parameters.

Wouldn't a "get_engine_par ...." instruction be missing ?

_  Serge

**Comment by faxinadu** [comment]
Which script are you referring to?

**Comment by faxinadu** [comment]
Thanks! Yes you are correct, fixed it now let me know if there are more problems there.
